### ISSUE TITLE
tb crashes on removing items from archive

### ISSUE THREAD

**Issue by AlexLov** [araaha/tb.go#3]
```
❯ tb archive
open /home/alex/.config/taskbook/taskbook.toml: no such file or directory

  Sun Aug 04 2024
    1.  test @test
    2.  test2 @test2
    3.  testd (!) @test2
    4.  testd3 (!!) @test2
    5. 󰎚 test note
    6. 󰎚 test note @test 󰓎

  0 of 0 tasks complete
  0 done · 0 in-progress · 0 pending · 0 notes

~ on  main
❯ tb archive --remove
open /home/alex/.config/taskbook/taskbook.toml: no such file or directory
panic: runtime error: slice bounds out of range [4:3]

goroutine 1 [running]:
github.com/araaha/tb.go/taskbook.(*Book).Remove(0xa182b0)
        github.com/araaha/tb.go/taskbook/taskbook.go:196 +0x1a5
github.com/araaha/tb.go/cmd.archive()
        github.com/araaha/tb.go/cmd/archive.go:21 +0x25
github.com/araaha/tb.go/cmd.init.func1(0xc000190100?, {0x75e494?, 0x4?, 0x75e498?})
        github.com/araaha/tb.go/cmd/archive.go:14 +0xf
github.com/spf13/cobra.(*Command).execute(0xa11580, {0xc00003a7e0, 0x1, 0x1})
        github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xa13240)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/araaha/tb.go/cmd.Execute()
        github.com/araaha/tb.go/cmd/root.go:49 +0x1a
main.main()
        github.com/araaha/tb.go/main.go:8 +0xf
~ on  main
❯
```

**Comment by araaha** [comment]
Thanks for the issues. I hastily didn't write tests before for archive but in hindsight I should've. Let me know if there are any other issues.
